version: '3'
services:
  rabbitmq:
    container_name: 'rabbit'
    image: rabbitmq:3-management
    hostname: 'rabbit'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./rabbitmq/rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq/log/:/var/log/rabbitmq

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  delivery_server:
    container_name: 'delivery_server'
    build:
      context: ./
    volumes:
      - .:/usr/src/app
    command: npm run start:delivery
    ports:
      - '3001:3001'
    depends_on:
      - rabbitmq

  kitchen_server:
    container_name: 'kitchen_server'
    build:
      context: ./
    volumes:
      - .:/usr/src/app
    command: npm run start:kitchen
    ports:
      - '3002:3002'
    depends_on:
      - rabbitmq

  orders_server:
    container_name: 'orders_server'
    build:
      context: ./
    volumes:
      - .:/usr/src/app
    command: npm run start:orders
    ports:
      - '3003:3003'
    env_file:
      - ./src/orders/.docker.env
    depends_on:
      - rabbitmq
