version: '3'
services:
  delivery_server:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start:delivery
    ports:
      - '3001:3001'
  kitchen_server:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start:kitchen
    ports:
      - '3002:3002'
  orders_server:
    build:
      context: ./
    volumes:
      - .:/src
    command: npm run start:orders
    ports:
      - '3003:3003'
    # depends_on:
    #   - postgres
    # environment:
    # DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos
